# Generated by Django 5.2 on 2025-05-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description_short', models.CharField(blank=True, verbose_name='Краткое описание')),
                ('description_long', models.CharField(blank=True, verbose_name='Полное описание')),
                ('lng', models.FloatField(verbose_name='Долгота(longitude)')),
                ('lat', models.FloatField(verbose_name='Широта(latitude)')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
