# Generated by Django 5.2 on 2025-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
