# Generated by Django 5.2 on 2025-05-07 11:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_placeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
